const StringResource = {
    admin: "Admin",
    requestedBookIds: "requestedBookIds",
    token: "AuthToken",
    linkAdminBookList: "/admin/books/",
    linkAdminBookCreate: "/admin/book/create/",
    linkAdminBookDelete: "/admin/book/delete/",
    linkAdminBookDetails: "/admin/book/details/",
    linkAdminBookEdit: "/admin/book/edit/",
    linkAdminCategoryCreate: "/admin/category/create/",
    linkAdminCategoryDetails: "/admin/category/details/",
    linkAdminCategoryEdit: "/admin/category/edit/",
    linkAdminCategoryList: "/admin/categories/",
    linkAdminRequestList: "/admin/requests/",
    linkAdminUserCreate: "/admin/user/create/",
    linkAdminUserDetails: "/admin/user/details/",
    linkAdminUserEdit: "/admin/user/edit/",
    linkAdminUserList: "/admin/users/",
    linkBook: "/books/",
    linkBookDetails: "/book/details/",
    linkCategory: "/categories/",
    linkCategoryDetails: "/category/details/",
    linkLogin: "/login/",
    linkLogout: "/logout/",
    linkHome: "/",
    linkNewRequest: "/new-request/",
    linkUserProfile: "/user-profile/"
};

export default StringResource;